services:
  mongo:
    image: mongo:7
    # pas de ports en CI
    # ports:
    #   - "27017:27017"

  backend:
    build: ./backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/shoe_store
      - JWT_SECRET=123456789
    # pas de ports en CI
    # ports:
    #   - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_ORIGIN=http://backend:5000
    # pas de ports en CI
    # ports:
    #   - "8080:80"
    depends_on:
      - backend

volumes:
  mongo_data:
  backend_uploads:
